/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> } 
 */
exports.seed = async function (knex) {

  await knex('team').insert([
    { code: 'UNDEF', name: 'Indefinido', imagePath: 'Flag_of_Default.svg', },

    { code: 'BRA', name: 'Brasil', imagePath: 'Flag_of_Brazil.svg', },
    { code: 'ARG', name: 'Argentina', imagePath: 'Flag_of_Argentina.svg', },
    { code: 'CHI', name: 'Chile', imagePath: 'Flag_of_Chile.svg', },
    { code: 'PER', name: 'Peru', imagePath: 'Flag_of_Peru.svg', },

    { code: 'URU', name: 'Uruguai', imagePath: 'Flag_of_Default.svg', },
    { code: 'RUS', name: 'Rússia', imagePath: 'Flag_of_Default.svg', },
    { code: 'KSA', name: 'Arábia Saudita', imagePath: 'Flag_of_Default.svg', },
    { code: 'EGY', name: 'Egito', imagePath: 'Flag_of_Default.svg', },
    { code: 'ESP', name: 'Espanha', imagePath: 'Flag_of_Default.svg', },
    { code: 'POR', name: 'Portugal', imagePath: 'Flag_of_Default.svg', },
    { code: 'IRN', name: 'Irã', imagePath: 'Flag_of_Default.svg', },
    { code: 'MAR', name: 'Marrocos', imagePath: 'Flag_of_Default.svg', },
    { code: 'FRA', name: 'França', imagePath: 'Flag_of_Default.svg', },
    { code: 'DEN', name: 'Dinamarca', imagePath: 'Flag_of_Default.svg', },
    { code: 'AUS', name: 'Austrália', imagePath: 'Flag_of_Default.svg', },
    { code: 'CRO', name: 'Croácia', imagePath: 'Flag_of_Default.svg', },
    { code: 'NGA', name: 'Nigéria', imagePath: 'Flag_of_Default.svg', },
    { code: 'ISL', name: 'Islândia', imagePath: 'Flag_of_Default.svg', },
    { code: 'SUI', name: 'Suíça', imagePath: 'Flag_of_Default.svg', },
    { code: 'SRB', name: 'Sérvia', imagePath: 'Flag_of_Default.svg', },
    { code: 'CRC', name: 'Costa Rica', imagePath: 'Flag_of_Default.svg', },
    { code: 'SWE', name: 'Suécia', imagePath: 'Flag_of_Default.svg', },
    { code: 'MEX', name: 'México', imagePath: 'Flag_of_Default.svg', },
    { code: 'KOR', name: 'Coreia do Sul', imagePath: 'Flag_of_Default.svg', },
    { code: 'GER', name: 'Alemanha', imagePath: 'Flag_of_Default.svg', },
    { code: 'BEL', name: 'Bélgica', imagePath: 'Flag_of_Default.svg', },
    { code: 'ENG', name: 'Inglaterra', imagePath: 'Flag_of_Default.svg', },
    { code: 'TUN', name: 'Tunísia', imagePath: 'Flag_of_Default.svg', },
    { code: 'PAN', name: 'Panamá', imagePath: 'Flag_of_Default.svg', },
    { code: 'COL', name: 'Colômbia', imagePath: 'Flag_of_Default.svg', },
    { code: 'JPN', name: 'Japão', imagePath: 'Flag_of_Default.svg', },
    { code: 'SEN', name: 'Senegal', imagePath: 'Flag_of_Default.svg', },
    { code: 'POL', name: 'Polônia', imagePath: 'Flag_of_Default.svg', },
    { code: 'CAN', name: 'Canadá', imagePath: 'Flag_of_Default.svg', },
    { code: 'VEN', name: 'Venezuela', imagePath: 'Flag_of_Default.svg', },
    { code: 'ECU', name: 'Equador', imagePath: 'Flag_of_Default.svg', },
    { code: 'JAM', name: 'Jamaica', imagePath: 'Flag_of_Default.svg', },
    { code: 'USA', name: 'Estados Unidos', imagePath: 'Flag_of_Default.svg', },
    { code: 'BOL', name: 'Bolívia', imagePath: 'Flag_of_Default.svg', },
    { code: 'PAR', name: 'Paraguai', imagePath: 'Flag_of_Default.svg', },
    { code: 'NED', name: 'Holanda', imagePath: 'Flag_of_Default.svg', },
    { code: 'QAT', name: 'Catar', imagePath: 'Flag_of_Default.svg', },
    { code: 'WAL', name: 'País de Gales', imagePath: 'Flag_of_Default.svg', },
    { code: 'CMR', name: 'Camarões', imagePath: 'Flag_of_Default.svg', },
    { code: 'GHA', name: 'Gana', imagePath: 'Flag_of_Default.svg', },
    { code: 'CZE', name: 'República Tcheca', imagePath: 'Flag_of_Default.svg', },
    { code: 'RSA', name: 'África do Sul', imagePath: 'Flag_of_Default.svg', },
    { code: 'BIH', name: 'Bósnia', imagePath: 'Flag_of_Default.svg', },
    { code: 'SCO', name: 'Escócia', imagePath: 'Flag_of_Default.svg', },
    { code: 'HAI', name: 'Haiti', imagePath: 'Flag_of_Default.svg', },
    { code: 'TUR', name: 'Turquia', imagePath: 'Flag_of_Default.svg', },
    { code: 'CIV', name: 'Costa do Marfim', imagePath: 'Flag_of_Default.svg', },
    { code: 'CUR', name: 'Curaçao', imagePath: 'Flag_of_Default.svg', },
    { code: 'NZL', name: 'Nova Zelândia', imagePath: 'Flag_of_Default.svg', },
    { code: 'CPV', name: 'Cabo Verde', imagePath: 'Flag_of_Default.svg', },
    { code: 'IRQ', name: 'Iraque', imagePath: 'Flag_of_Default.svg', },
    { code: 'NOR', name: 'Noruega', imagePath: 'Flag_of_Default.svg', },
    { code: 'ALG', name: 'Argélia', imagePath: 'Flag_of_Default.svg', },
    { code: 'JOR', name: 'Jordânia', imagePath: 'Flag_of_Default.svg', },
    { code: 'AUT', name: 'Áustria', imagePath: 'Flag_of_Default.svg', },
    { code: 'COD', name: 'RD Congo', imagePath: 'Flag_of_Default.svg', },
    { code: 'UZB', name: 'Uzbequistão', imagePath: 'Flag_of_Default.svg', },
  ]);

};
