const helper = require('../helpers');
/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> } 
 */
exports.seed = async function (knex) {
  const h = new helper(knex);

  await h.runOrLog(knex('team').insert([
    { code: 'UNDEF', name: 'Indefinido', imagePath: 'default_flag.png', },

    { code: 'BRA', name: 'Brasil', imagePath: 'Flag_of_Brazil.svg', },
    { code: 'ARG', name: 'Argentina', imagePath: 'Flag_of_Argentina.svg', },
    { code: 'CHI', name: 'Chile', imagePath: 'Flag_of_Chile.svg', },
    { code: 'PER', name: 'Peru', imagePath: 'Flag_of_Peru.svg', },

    { code: 'URU', name: 'Uruguai', imagePath: 'Flag_of_Uruguay.svg', },
    { code: 'RUS', name: 'Rússia', imagePath: 'Flag_of_Russia.svg', },
    { code: 'KSA', name: 'Arábia Saudita', imagePath: 'Flag_of_Saudi_Arabia.svg', },
    { code: 'EGY', name: 'Egito', imagePath: 'Flag_of_Egypt.svg', },
    { code: 'ESP', name: 'Espanha', imagePath: 'Flag_of_Spain.svg', },
    { code: 'POR', name: 'Portugal', imagePath: 'Flag_of_Portugal.svg', },
    { code: 'IRN', name: 'Irã', imagePath: 'Flag_of_Iran.svg', },
    { code: 'MAR', name: 'Marrocos', imagePath: 'Flag_of_Morocco.svg', },
    { code: 'FRA', name: 'França', imagePath: 'Flag_of_France.svg', },
    { code: 'DEN', name: 'Dinamarca', imagePath: 'Flag_of_Denmark.svg', },
    { code: 'AUS', name: 'Austrália', imagePath: 'Flag_of_Australia.svg', },
    { code: 'CRO', name: 'Croácia', imagePath: 'Flag_of_Croatia.svg', },
    { code: 'NGA', name: 'Nigéria', imagePath: 'Flag_of_Nigeria.svg', },
    { code: 'ISL', name: 'Islândia', imagePath: 'Flag_of_Iceland.svg', },
    { code: 'SUI', name: 'Suíça', imagePath: 'Flag_of_Switzerland.svg', },
    { code: 'SRB', name: 'Sérvia', imagePath: 'Flag_of_Serbia.svg', },
    { code: 'CRC', name: 'Costa Rica', imagePath: 'Flag_of_Costa_Rica.svg', },
    { code: 'SWE', name: 'Suécia', imagePath: 'Flag_of_Sweden.svg', },
    { code: 'MEX', name: 'México', imagePath: 'Flag_of_Mexico.svg', },
    { code: 'KOR', name: 'Coreia do Sul', imagePath: 'Flag_of_South_Korea.svg', },
    { code: 'GER', name: 'Alemanha', imagePath: 'Flag_of_Germany.svg', },
    { code: 'BEL', name: 'Bélgica', imagePath: 'Flag_of_Belgium.svg', },
    { code: 'ENG', name: 'Inglaterra', imagePath: 'Flag_of_England.svg', },
    { code: 'TUN', name: 'Tunísia', imagePath: 'Flag_of_Tunisia.svg', },
    { code: 'PAN', name: 'Panamá', imagePath: 'Flag_of_Panama.svg', },
    { code: 'COL', name: 'Colômbia', imagePath: 'Flag_of_Colombia.svg', },
    { code: 'JPN', name: 'Japão', imagePath: 'Flag_of_Japan.svg', },
    { code: 'SEN', name: 'Senegal', imagePath: 'Flag_of_Senegal.svg', },
    { code: 'POL', name: 'Polônia', imagePath: 'Flag_of_Poland.svg', },
    { code: 'CAN', name: 'Canadá', imagePath: 'Flag_of_Canada.svg', },
    { code: 'VEN', name: 'Venezuela', imagePath: 'Flag_of_Venezuela.svg', },
    { code: 'ECU', name: 'Equador', imagePath: 'Flag_of_Ecuador.svg', },
    { code: 'JAM', name: 'Jamaica', imagePath: 'Flag_of_Jamaica.svg', },
    { code: 'USA', name: 'Estados Unidos', imagePath: 'Flag_of_the_United_States.svg', },
    { code: 'BOL', name: 'Bolívia', imagePath: 'Flag_of_Bolivia.svg', },
    { code: 'PAR', name: 'Paraguai', imagePath: 'Flag_of_Paraguay.svg', },
    { code: 'NED', name: 'Holanda', imagePath: 'Flag_of_the_Netherlands.svg', },
    { code: 'QAT', name: 'Catar', imagePath: 'Flag_of_Qatar.svg', },
    { code: 'WAL', name: 'País de Gales', imagePath: 'Flag_of_Wales.svg', },
    { code: 'CMR', name: 'Camarões', imagePath: 'Flag_of_Cameroon.svg', },
    { code: 'GHA', name: 'Gana', imagePath: 'Flag_of_Ghana.svg', },
    { code: 'CZE', name: 'República Tcheca', imagePath: 'Flag_of_the_Czech_Republic.svg', },
    { code: 'RSA', name: 'África do Sul', imagePath: 'Flag_of_South_Africa.svg', },
    { code: 'BIH', name: 'Bósnia', imagePath: 'Flag_of_Bosnia_and_Herzegovina.svg', },
    { code: 'SCO', name: 'Escócia', imagePath: 'Flag_of_Scotland.svg', },
    { code: 'HAI', name: 'Haiti', imagePath: 'Flag_of_Haiti.svg', },
    { code: 'TUR', name: 'Turquia', imagePath: 'Flag_of_Turkey.svg', },
    { code: 'CIV', name: 'Costa do Marfim', imagePath: 'Flag_of_Cote_d_Ivoire.png', },
    { code: 'CUR', name: 'Curaçao', imagePath: 'Flag_of_Curacao.svg', },
    { code: 'NZL', name: 'Nova Zelândia', imagePath: 'Flag_of_New_Zealand.svg', },
    { code: 'CPV', name: 'Cabo Verde', imagePath: 'Flag_of_Cape_Verde.svg', },
    { code: 'IRQ', name: 'Iraque', imagePath: 'Flag_of_Iraq.svg', },
    { code: 'NOR', name: 'Noruega', imagePath: 'Flag_of_Norway.svg', },
    { code: 'ALG', name: 'Argélia', imagePath: 'Flag_of_Algeria.svg', },
    { code: 'JOR', name: 'Jordânia', imagePath: 'Flag_of_Jordan.svg', },
    { code: 'AUT', name: 'Áustria', imagePath: 'Flag_of_Austria.svg', },
    { code: 'COD', name: 'RD Congo', imagePath: 'Flag_of_the_Republic_of_the_Congo.svg', },
    { code: 'UZB', name: 'Uzbequistão', imagePath: 'Flag_of_Uzbekistan.svg', },
  ]));
};
